CREATE OR REPLACE PROCEDURE CREATE_SEQUENCE(
    TABLE_NAME IN VARCHAR2
)
    IS
    SEQUENCE_COUNTER     NUMBER;
    CUSTOM_SEQUENCE_NAME VARCHAR2(100) := TABLE_NAME || '_ID_SEQUENCE';
BEGIN

    SELECT COUNT(1)
    INTO SEQUENCE_COUNTER
    FROM USER_SEQUENCES
    WHERE UPPER(SEQUENCE_NAME) = UPPER(CUSTOM_SEQUENCE_NAME);

    IF SEQUENCE_COUNTER = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE ' || CUSTOM_SEQUENCE_NAME;
    END IF;

    COMMIT;
END;