CREATE OR REPLACE PROCEDURE save_process_log
(
  PROCESS_NAME  VARCHAR2(30),
    START_DATE DATE,
    END_DATE DATE,
    QUANTITY_ROWS NUMBER(10),
    PROCESS_MESSAGE  VARCHAR2(255),
    EXECUTED_SUCCESS VARCHAR(1),
    NUMBER_OF_DIFFERENCES NUMBER(10)
)
AS
DECLARE
    V_PROCESS_NAME          VARCHAR2(30):= @PROCESS_NAME;
    V_START_DATE            DATE:= @START_DATE;
    V_END_DATE              DATE:= @END_DATE;
    V_PROCESS_MESSAGE       VARCHAR2(255):= @PROCESS_MESSAGE;
    V_QUANTITY_ROWS         NUMBER(10) := @QUANTITY_ROWS;
    V_EXECUTED_SUCCESS      VARCHAR2(1) := @EXECUTED_SUCCESS;
    v_NUMBER_OF_DIFFERENCES NUMBER(10) := @NUMBER_OF_DIFFERENCES;
BEGIN
END save_process_log;