CREATE OR REPLACE PROCEDURE SAVE_PROCESS_LOG(
    P_PROCESS_NAME IN VARCHAR2,
    P_START_DATE IN DATE,
    P_END_DATE IN DATE,
    P_QUANTITY_ROWS IN NUMBER,
    P_PROCESS_MESSAGE IN VARCHAR2,
    P_EXECUTED_SUCCESS IN VARCHAR,
    P_NUMBER_OF_DIFFERENCES IN NUMBER
)
AS
BEGIN
    INSERT INTO  STG_PROCESS_LOG
    VALUES (P_PROCESS_NAME, P_START_DATE, P_END_DATE,P_QUANTITY_ROWS, P_PROCESS_MESSAGE,P_EXECUTED_SUCCESS, P_NUMBER_OF_DIFFERENCES);
    COMMIT;
END;