--Schema creation of Stage

CREATE TABLE STG_CATEGORIES
NOLOGGING
AS
SELECT * FROM ORDERS_DB.CATEGORIES
where rownum<1 ;

CREATE TABLE STG_CUSTOMERS
NOLOGGING
AS
SELECT * FROM ORDERS_DB.CUSTOMERS
where rownum<1  ;

CREATE TABLE STG_EMPLOYEES(
    EMPLOYEEID         NUMBER(38, 0)    NOT NULL,
    LASTNAME           VARCHAR2(20)     NOT NULL,
    FIRSTNAME          VARCHAR2(10)     NOT NULL,
    TITLE              VARCHAR2(30),
    TITLEOFCOURTESY    VARCHAR2(25),
    BIRTHDATE          DATE,
    HIREDATE           DATE,
    ADDRESS            VARCHAR2(60),
    CITY               VARCHAR2(15),
    REGION             VARCHAR2(15),
    POSTALCODE         VARCHAR2(10),
    COUNTRY            VARCHAR2(15),
    HOMEPHONE          VARCHAR2(24),
    EXTENSION          VARCHAR2(4),
    NOTES              LONG,
    REPORTSTO          NUMBER(38, 0),
    CONSTRAINT PK_EMPLOYEES PRIMARY KEY (EMPLOYEEID)
);

CREATE TABLE STG_ORDERDETAILS
NOLOGGING
AS
SELECT * FROM ORDERS_DB.ORDERDETAILS
where rownum<1 ;


CREATE TABLE STG_ORDERS
NOLOGGING
AS
SELECT * FROM ORDERS_DB.ORDERS
where rownum<1 ;


CREATE TABLE STG_PRODUCTS
NOLOGGING
AS
SELECT * FROM ORDERS_DB.PRODUCTS
where rownum<1 ;


CREATE TABLE STG_SHIPPERS
NOLOGGING
AS
SELECT * FROM ORDERS_DB.SHIPPERS
where rownum<1;

CREATE TABLE STG_SUPPLIERS
NOLOGGING
AS
SELECT * FROM ORDERS_DB.SUPPLIERS
where rownum<1 ;

--- Copy of the dimension tables from Star Schema


CREATE TABLE STG_DIM_CUSTOMERS
NOLOGGING
AS
SELECT * FROM STAR.DIM_CUSTOMERS
where rownum<1 ;

CREATE TABLE STG_DIM_EMPLOYEES(
    EMPLOYEE_IDW       NUMBER(10, 0)    NOT NULL,
    EMPLOYEEID         NUMBER(38, 0)    NOT NULL,
    LASTNAME           VARCHAR2(20)     NOT NULL,
    FIRSTNAME          VARCHAR2(10)     NOT NULL,
    TITLE              VARCHAR2(30),
    TITLEOFCOURTESY    VARCHAR2(25),
    BIRTHDATE          DATE,
    HIREDATE           DATE,
    ADDRESS            VARCHAR2(60),
    CITY               VARCHAR2(15),
    REGION             VARCHAR2(15),
    POSTALCODE         VARCHAR2(10),
    COUNTRY            VARCHAR2(15),
    HOMEPHONE          VARCHAR2(24),
    EXTENSION          VARCHAR2(4),
    NOTES              LONG,
    REPORTSTO          NUMBER(38, 0),
    CONSTRAINT PK_EMPLOYEES_1 PRIMARY KEY (EMPLOYEE_IDW)
);

CREATE TABLE STG_DIM_GEOGRAFIA
NOLOGGING
AS
SELECT * FROM STAR.DIM_GEOGRAFIA
where rownum<1 ;

CREATE TABLE STG_DIM_PRODUCTS
NOLOGGING
AS
SELECT * FROM STAR.DIM_PRODUCTS
where rownum<1 ;

CREATE TABLE STG_DIM_SHIPPERS
NOLOGGING
AS
SELECT * FROM STAR.DIM_SHIPPERS
where rownum<1 ;

CREATE TABLE STG_DIM_TIEMPO
NOLOGGING
AS
SELECT * FROM STAR.DIM_TIEMPO
where rownum<1 ;

CREATE TABLE STG_FACT_ORDERS
NOLOGGING
AS
SELECT * FROM STAR.FACT_ORDERS
where rownum<1 ;


CREATE TABLE STG_DIM_SHIPPERS
NOLOGGING
AS
SELECT * FROM STAR.DIM_SHIPPERS
where rownum<1 ;

CREATE TABLE STG_PROCESS_LOG(
    PROCESS_NAME  VARCHAR2(30),
    START_DATE DATE,
    END_DATE DATE,
    QUANTITY_ROWS NUMBER(10),
    PROCESS_MESSAGE  VARCHAR2(255),
    EXECUTED_SUCCESS VARCHAR(1),
    NUMBER_OF_DIFFERENCES NUMBER(10)
);