
-- Date Created : Thursday, May 05, 2022 07:24:43
-- Target DBMS : Oracle 11g
--

--
-- TABLE: DIM_CUSTOMERS
--

CREATE TABLE DIM_CUSTOMERS(
    CUSTOMER_IDW        NUMBER(10, 0)    NOT NULL,
    CUSTOMERID          VARCHAR2(5)      NOT NULL,
    CUSTOMER            VARCHAR2(40)     NOT NULL,
    CUSTOMER_CONTACT    VARCHAR2(30),
    CONTACTTITLE        VARCHAR2(30),
    ADDRESS             VARCHAR2(60),
    CITY                VARCHAR2(15),
    REGION              VARCHAR2(15),
    POSTALCODE          VARCHAR2(10),
    COUNTRY             VARCHAR2(15),
    PHONE               VARCHAR2(24),
    FAX                 VARCHAR2(24),
    LOG_USER            CHAR(10),
    START_DATE          DATE,
    END_DATE            DATE,
    CURRENT_FLAG        VARCHAR2(1),
    PK_SYSTEM_SOURCE    NUMBER(10, 0),
    SYSTEM_SOURCE       VARCHAR2(100),
    CONSTRAINT PK_CUSTOMER_1 PRIMARY KEY (CUSTOMER_IDW)
)
;



--
-- TABLE: DIM_EMPLOYEES
--

CREATE TABLE DIM_EMPLOYEES(
    EMPLOYEE_IDW       NUMBER(10, 0)    NOT NULL,
    EMPLOYEEID         NUMBER(38, 0)    NOT NULL,
    LASTNAME           VARCHAR2(20)     NOT NULL,
    FIRSTNAME          VARCHAR2(10)     NOT NULL,
    TITLE              VARCHAR2(30),
    TITLEOFCOURTESY    VARCHAR2(25),
    BIRTHDATE          DATE,
    HIREDATE           DATE,
    ADDRESS            VARCHAR2(60),
    CITY               VARCHAR2(15),
    REGION             VARCHAR2(15),
    POSTALCODE         VARCHAR2(10),
    COUNTRY            VARCHAR2(15),
    HOMEPHONE          VARCHAR2(24),
    EXTENSION          VARCHAR2(4),
    NOTES              LONG,
    REPORTSTO          NUMBER(38, 0),
    CONSTRAINT PK_EMPLOYEES_1 PRIMARY KEY (EMPLOYEE_IDW)
);



--
-- TABLE: DIM_GEOGRAFIA
--

CREATE TABLE DIM_GEOGRAFIA(
    GEOGRAFIA_IDW    NUMBER(10, 0)    NOT NULL,
    ADRESS           VARCHAR2(200),
    CITY             VARCHAR2(200),
    REGION           VARCHAR2(200),
    POSTALCODE       VARCHAR2(100),
    COUNTRY          VARCHAR2(100),
    CONSTRAINT PK24 PRIMARY KEY (GEOGRAFIA_IDW)
)
;



--
-- TABLE: DIM_PRODUCTS
--

CREATE TABLE DIM_PRODUCTS(
    PRODUCT_IDW             NUMBER(10, 0)    NOT NULL,
    PRODUCTID               NUMBER(38, 0)    NOT NULL,
    PRODUCTNAME             VARCHAR2(40)     NOT NULL,
    QUANTITYPERUNIT         VARCHAR2(20),
    UNITPRICE               NUMBER(19, 2)    DEFAULT 0,
    UNITSINSTOCK            NUMBER(5, 0)     DEFAULT 0,
    UNITSONORDER            NUMBER(5, 0)     DEFAULT 0,
    REORDERLEVEL            NUMBER(5, 0)     DEFAULT 0,
    DISCONTINUED            NUMBER(1, 0),
    CATEGORYID              NUMBER(38, 0),
    CATEGORYNAME            VARCHAR2(100),
    DESCRIPTION_CATEGORY    VARCHAR2(200),
    SUPPLIERID              NUMBER(38, 0),
    SUPPLIER                VARCHAR2(100),
    SUPPLIERCONTACT         VARCHAR2(100),
    SUPPLIERTITLE           VARCHAR2(100),
    ADDRES                  VARCHAR2(100),
    CITY                    VARCHAR2(100),
    REGION                  VARCHAR2(100),
    POSTALCODE              VARCHAR2(100),
    COUNTRY                 VARCHAR2(100),
    PHONE                   VARCHAR2(100),
    FAX                     VARCHAR2(100),
    CONSTRAINT PK_PRODUCTS_1 PRIMARY KEY (PRODUCT_IDW)
)
;



--
-- TABLE: DIM_SHIPPERS
--

CREATE TABLE DIM_SHIPPERS(
    IDW_SHIPPERS    NUMBER(10, 0)    NOT NULL,
    SHIPPERID       NUMBER(38, 0)    NOT NULL,
    SHIPPERS        VARCHAR2(40)     NOT NULL,
    PHONE           VARCHAR2(24),
    CONSTRAINT PKPRODUCTS_1 PRIMARY KEY (IDW_SHIPPERS)
)
;



--
-- TABLE: DIM_TIEMPO
--

CREATE TABLE DIM_TIEMPO(
    fecha         DATE             NOT NULL,
    dianro        NUMBER(10, 0),
    diasemana     VARCHAR2(50),
    dialaboral    VARCHAR2(1),
    feriado       VARCHAR2(1),
    finsemana     VARCHAR2(1),
    mesnro        NUMBER(10, 0),
    Mes           VARCHAR2(10),
    periodo       VARCHAR2(10),
    quarter       VARCHAR2(10),
    semester      VARCHAR2(10),
    Anio          NUMBER(10, 0),
    CONSTRAINT PK_FECHA PRIMARY KEY (fecha)
)
;



--
-- TABLE: FACT_ORDERS
--

CREATE TABLE FACT_ORDERS(
    ORDERID          NUMBER(38, 0)    NOT NULL,
    CUSTOMERID       VARCHAR2(5),
    EMPLOYEEID       NUMBER(38, 0),
    ORDERDATE        DATE             NOT NULL,
    REQUIREDDATE     DATE             NOT NULL,
    SHIPPEDDATE      DATE             NOT NULL,
    SHIPVIA          NUMBER(38, 0),
    FREIGHT          NUMBER(19, 2)    DEFAULT 0,
    SHIPNAME         VARCHAR2(40),
    UNITPRICE        NUMBER(25, 0),
    QUANTITY         NUMBER(10, 0),
    DISCOUNT         NUMBER(10, 0),
    CUSTOMER_IDW     NUMBER(10, 0)    NOT NULL,
    EMPLOYEE_IDW     NUMBER(10, 0)    NOT NULL,
    PRODUCT_IDW      NUMBER(10, 0)    NOT NULL,
    IDW_SHIPPERS     NUMBER(10, 0)    NOT NULL,
    GEOGRAFIA_IDW    NUMBER(10, 0)    NOT NULL,
    FECHA_CARGA      DATE
)
;



--
-- TABLE: FACT_ORDERS
--

ALTER TABLE FACT_ORDERS ADD CONSTRAINT RefDIM_CUSTOMERS11
    FOREIGN KEY (CUSTOMER_IDW)
    REFERENCES DIM_CUSTOMERS(CUSTOMER_IDW)
;

ALTER TABLE FACT_ORDERS ADD CONSTRAINT RefDIM_EMPLOYEES21
    FOREIGN KEY (EMPLOYEE_IDW)
    REFERENCES DIM_EMPLOYEES(EMPLOYEE_IDW)
;

ALTER TABLE FACT_ORDERS ADD CONSTRAINT RefDIM_PRODUCTS31
    FOREIGN KEY (PRODUCT_IDW)
    REFERENCES DIM_PRODUCTS(PRODUCT_IDW)
;

ALTER TABLE FACT_ORDERS ADD CONSTRAINT RefDIM_SHIPPERS41
    FOREIGN KEY (IDW_SHIPPERS)
    REFERENCES DIM_SHIPPERS(IDW_SHIPPERS)
;

ALTER TABLE FACT_ORDERS ADD CONSTRAINT RefDIM_GEOGRAFIA51
    FOREIGN KEY (GEOGRAFIA_IDW)
    REFERENCES DIM_GEOGRAFIA(GEOGRAFIA_IDW)
;

ALTER TABLE FACT_ORDERS ADD CONSTRAINT RefDIM_TIEMPO61
    FOREIGN KEY (REQUIREDDATE)
    REFERENCES DIM_TIEMPO(fecha)
;

ALTER TABLE FACT_ORDERS ADD CONSTRAINT RefDIM_TIEMPO71
    FOREIGN KEY (ORDERDATE)
    REFERENCES DIM_TIEMPO(fecha)
;

ALTER TABLE FACT_ORDERS ADD CONSTRAINT RefDIM_TIEMPO81
    FOREIGN KEY (SHIPPEDDATE)
    REFERENCES DIM_TIEMPO(fecha)
;

