SELECT 'GRANT SELECT, INSERT, UPDATE ON '||TABLE_NAME||' TO STAGE;' FROM USER_TABLES;

GRANT SELECT, INSERT, UPDATE ON DIM_CUSTOMERS TO STAGE;
GRANT SELECT, INSERT, UPDATE ON DIM_EMPLOYEES TO STAGE;
GRANT SELECT, INSERT, UPDATE ON DIM_GEOGRAFIA TO STAGE;
GRANT SELECT, INSERT, UPDATE ON DIM_PRODUCTS TO STAGE;
GRANT SELECT, INSERT, UPDATE ON DIM_SHIPPERS TO STAGE;
GRANT SELECT, INSERT, UPDATE ON DIM_TIEMPO TO STAGE;
GRANT SELECT, INSERT, UPDATE ON FACT_ORDERS TO STAGE;
