CREATE OR REPLACE PROCEDURE LOAD_STAR_DIM_EMPLOYEE
IS
    V_PROCESS_NAME          VARCHAR2(30) := $$plsql_unit;
    V_START_DATE            DATE;
    V_END_DATE              DATE;
    V_PROCESS_MESSAGE       VARCHAR2(255) := 'Process '|| $$plsql_unit || ' run successfully';
    V_QUANTITY_ROWS         NUMBER(10)    := 0;
    V_EXECUTED_SUCCESS      VARCHAR2(1)   := 'Y';
    v_NUMBER_OF_DIFFERENCES NUMBER(10)    := 0;
BEGIN
    V_START_DATE := SYSDATE;

    DECLARE
        CURSOR EMPLOYEES_CURSOR
        IS
            SELECT EMPLOYEE_IDW, EMPLOYEEID, LASTNAME, FIRSTNAME, TITLE, TITLEOFCOURTESY, BIRTHDATE
                   , HIREDATE , ADDRESS, CITY, REGION, POSTALCODE, COUNTRY, HOMEPHONE, EXTENSION,  REPORTSTO
            FROM STG_DIM_EMPLOYEES
            MINUS
              SELECT EMPLOYEE_IDW, EMPLOYEEID, LASTNAME, FIRSTNAME, TITLE, TITLEOFCOURTESY, BIRTHDATE
                   , HIREDATE , ADDRESS, CITY, REGION, POSTALCODE, COUNTRY, HOMEPHONE, EXTENSION,  REPORTSTO
            FROM STAR.DIM_EMPLOYEES;
        BEGIN
            FOR EMPLOYEE IN EMPLOYEES_CURSOR LOOP
                IF EMPLOYEE.EMPLOYEE_IDW != -1 THEN
                    UPDATE STAR.DIM_EMPLOYEES
                    SET EMPLOYEEID = EMPLOYEE.EMPLOYEEID,
                        LASTNAME = EMPLOYEE.LASTNAME,
                        FIRSTNAME = EMPLOYEE.LASTNAME,
                        TITLE = EMPLOYEE.TITLE,
                        TITLEOFCOURTESY = EMPLOYEE.TITLEOFCOURTESY,
                        BIRTHDATE = EMPLOYEE.BIRTHDATE,
                        HIREDATE = EMPLOYEE.HIREDATE,
                        ADDRESS = EMPLOYEE.ADDRESS,
                        CITY = EMPLOYEE.CITY,
                        REGION = EMPLOYEE.REGION,
                        POSTALCODE = EMPLOYEE.POSTALCODE,
                        COUNTRY = EMPLOYEE.COUNTRY,
                        HOMEPHONE = EMPLOYEE.HOMEPHONE,
                        EXTENSION = EMPLOYEE.EXTENSION,
                        REPORTSTO = EMPLOYEE.REPORTSTO
                    WHERE EMPLOYEE_IDW = EMPLOYEE.EMPLOYEE_IDW;
                    COMMIT;
                    v_NUMBER_OF_DIFFERENCES := v_NUMBER_OF_DIFFERENCES + 1;
                END IF;
            END LOOP;
            INSERT INTO STAR.DIM_EMPLOYEES(EMPLOYEE_IDW, EMPLOYEEID, LASTNAME, FIRSTNAME, TITLE, TITLEOFCOURTESY, BIRTHDATE
                   , HIREDATE , ADDRESS, CITY, REGION, POSTALCODE, COUNTRY, HOMEPHONE, EXTENSION, REPORTSTO)
                SELECT EMPLOYEE_IDW, EMPLOYEEID, LASTNAME, FIRSTNAME, TITLE, TITLEOFCOURTESY, BIRTHDATE
                   , HIREDATE , ADDRESS, CITY, REGION, POSTALCODE, COUNTRY, HOMEPHONE, EXTENSION, REPORTSTO FROM STG_DIM_EMPLOYEES;

            V_END_DATE := SYSDATE;
            V_QUANTITY_ROWS := SQL%ROWCOUNT;

            SAVE_PROCESS_LOG(V_PROCESS_NAME, V_START_DATE, V_END_DATE,  V_QUANTITY_ROWS,V_PROCESS_MESSAGE, V_EXECUTED_SUCCESS,v_NUMBER_OF_DIFFERENCES);

            COMMIT;
        EXCEPTION
            WHEN OTHERS THEN
            V_END_DATE := SYSDATE;
            V_PROCESS_MESSAGE := ('There were and error while executing ' || $$plsql_unit || ' procedure '||SQLCODE||' '||SQLERRM|| ' ');
            V_EXECUTED_SUCCESS := 'N';
            SAVE_PROCESS_LOG(V_PROCESS_NAME, V_START_DATE, V_END_DATE,  V_QUANTITY_ROWS,V_PROCESS_MESSAGE, V_EXECUTED_SUCCESS,v_NUMBER_OF_DIFFERENCES);
        END;
END;